file = open ("employees.txt","w")
file.write("1,ABC,20000\n")
file.write("2,XYZ,30000\n")
file.close()
file=open("employees.txt","r")
print("Employee Records:")
print(file.read())
file.close()
file=open("employees.txt","a")
file.write("3,EFG,25000\n")
file.close()
file=open("employees.txt","r")
print("Updates employees records:")
print(file.read())
file.close()